### ISSUE TITLE
 MPF.Media.Sounds supporting looping of audiostreamrandomiser?

### ISSUE THREAD

**Issue by DorusvdLinden** [missionpinball/mpf-gmc#15]
Dear all,

I love the new setup, but i have one issue:
In my previous iteration I was looping multiple sounds in attract mode randomly, to create a dynamic background. 

Now in Godot, the individual wav files can loop, but the audiostreamrandomiser stops after 1 sound played.

Using loops: -1, 3 or true gives an error in the MPF.Media.Sounds code (GMCChannel.gd) in mpf-gmc/scripts/)
![Screenshot 2024-09-14 153948](https://github.com/user-attachments/assets/49fabd00-67ae-4702-aff9-1107fb557c3c)

![Screenshot 2024-09-14 153751](https://github.com/user-attachments/assets/99cb1399-8a27-4419-81b3-43dcaba2f8ff)

code:
```
sound_player:
  mode_attract_started:
    SlowMusic:
      bus: music
      loops: 3
```

without the loops it runs fine.
Could be my mistake.
Kind regards
Dorus

**Comment by avanwinkle** [comment]
Thanks for opening this issue! There were some challenges with getting loops to behave "MPF style" in GMC, and I set that work aside to finish out other features. I've been thinking on it and your notes here have given me an idea on how to implement loops in a better way, so I'll keep you updated with how it goes!

**Comment by DorusvdLinden** [comment]
Thank you @avanwinkle, for the update.
Loops: 3 works now on AudioStreamRandomizer.
Loops: -1 gives the same old error:
<img width="704" alt="image" src="https://github.com/user-attachments/assets/e09ed2b4-e29b-4a5a-9d5e-95ef60734d0b">
Not sure if AudioStreamRandomizer supports "self.stream.loop=true"
The work around is adding a high number of loops.

**Comment by avanwinkle** [comment]
That's a curious error, because AudioStreamRandomizer inherits from AudioStream, as do AudioStreamOggVorbis and AudioStreamMP3, but the randomizer does _not_ inherit from either of those so it shouldn't be entering this code block if `self.stream` is a randomizer.

There's an argument to be made for always doing the manual looping instead of relying on the Ogg/MP3/Wav built-in method, but I'll investigate a little more first.

**Comment by avanwinkle** [comment]
Okay, my bad. I had a shorthand in the condition that was always returning true and trying to treat the resource as an Ogg/Wav. Fixed that and verified that AudioStreamRandomizer now can loop indefinitely.

**Comment by DorusvdLinden** [comment]
Great to hear. I will test it in the weekend. Thank you for the fast response. Ps: I really like the new setup.

**Comment by DorusvdLinden** [comment]
Thank you so much, the loop: -1 now also works.
Great to see how fast this evolves.
