### ISSUE TITLE
Carousel, highlights and start game not working.

### ISSUE THREAD

**Issue by Pucksnok** [missionpinball/mpf-gmc#17]
Hello.
I have an issue when using carousel mode with attract. When I use carousel in attract mode I can't start a game, usually it gives some error but here it's nothing. I do see that the switch is active and correctly named. If I exclude the carousel parts it can start game and starts the base mode without any issues.

I have tried replacing the addons folder.
I have tried do a completely new attract.yaml and attract.tscn
I have tried an attract scene with only a background but still using the carousel active in attract.yaml.
I have tried to use files for carousel provided by Atummons on the Trident Pinball discord, see files in zip.
[attract.zip](https://github.com/user-attachments/files/17871302/attract.zip)

What I also see is that the old carousel highlights isn't working.

event_player:
     carousel_MPFSlide_highlighted: test_event
     carousel_MPFSlide2_highlighted: test_event2
     carousel_MPFSlide3_highlighted: test_event3

None of the events are posted when doing highlight like in 0.54.

My switch works, I see it in both the graphical interface of mpf and the logs/text prompt.

switches:
    s_start_button:
        number: 3-0-21
        tags: start
s_start_button shows up as active in both mpf logs and the gmc output. I also see it being pressed if I use the graphical ui of mpf.

Is this some bug or am I just stupid? I have done what I can to do everything as basic as possible in my code replacing everything in my attract and base mode, makes no difference, all I can do is to skip the carousel.

Sorry for that the code looks wrong, it looks correct in my windows but not when posted.

Cheers.

**Comment by Pucksnok** [comment]
Godot v4.3.stable.official [77dcf97d8]
Mission Pinball Framework v0.80.0.dev5

**Comment by avanwinkle** [comment]
As for the carousel item highlights, those are changed in 0.80 to use a single standard event _item_highlighted_ and arguments to identify the carousel (mode name) and the item. So if your mode name is "attract" and your highlighted item is "MPFSlide2", you should see an event in your logs like this:

```
item_highlighted{carousel: 'attract', direction: 'forward', item: 'MPFSlide2'}
```

**Comment by Pucksnok** [comment]
Thank you! I removed "code: mpf.modes.carousel.code.carousel.Carousel" and it now works again. highlight also works. Much appreciated.
