### ISSUE TITLE
MPFConditional bug, maybe provided solution

### ISSUE THREAD

**Issue by Pucksnok** [missionpinball/mpf-gmc#18]
Hello.
I think I've encountered some misstake in the code. I have been working to try and use machine variables with MPFConditional, but it crashes all the time when I use it.

![image](https://github.com/user-attachments/assets/7bd3e76d-bb44-4611-a80c-83264b0712e1)

I then checked the mpf_variable.gd which actually works with machine variables. At line 99 it say value = MPF.game.machine_vars
![image](https://github.com/user-attachments/assets/920b90f4-d55c-4d31-83cf-59dfab0e86c4)

If I then go back to mpf_conditional.gd and change line 104 to base = MPF.game.machine_vars

![image](https://github.com/user-attachments/assets/3063afc9-d24b-48bf-a3ea-93469309234e)

Now MPFConditional doesn't crash and it seems to work as it should. If I check the condition on a machine variable with MPFConditional it works as expected, I have tried with different values that's both true and false. Works as it should with the change.
I guess this is a bug. I'm no programmer so hopefully you can check it and verify. I'm useless at GitHub so an issue is all you get from me.

Cheers.

/Johan Gill

**Comment by avanwinkle** [comment]
Great find! You are correct, and I've pushed an update to reference the proper name `MPF.game.machine_vars`. Thanks!
