### ISSUE TITLE
When adding an MPFEventHandler configured to listen to player_added results in an error in the GMCServer

### ISSUE THREAD

**Issue by bernarma** [missionpinball/mpf-gmc#19]
Start the game and add more than 1 player.

Without Handler
```
13:52:33.214 : DEBUG : GMCServer : { "player_num": 1, "cmd": "player_added" }
13:52:40.543 : DEBUG : GMCServer : { "player_num": 2, "cmd": "player_added" }
13:52:41.850 : DEBUG : GMCServer : { "player_num": 3, "cmd": "player_added" }
13:52:42.822 : DEBUG : GMCServer : { "player_num": 4, "cmd": "player_added" }
```

With Handler
```
13:55:40.844 : DEBUG : GMCServer : { "player_num": 1, "cmd": "player_added" }
13:55:42.387 : DEBUG : GMCServer : { "player_num": 2, "cmd": "player_added" }
13:55:42.387 : DEBUG : GMCServer : { "name": "player_added", "player": "<Player 2>", "num": 2, "cmd": "player_added" }
```

This code fails when attempting to access the player_num property.

```
func add_player(kwargs: Dictionary) -> void:
	players.append({
		"score": 0,
		"number": kwargs.player_num
	})
	num_players = players.size()
	emit_signal("player_added", num_players)

```

Using the latest Godot MC and MPF (0.8+) versions.

**Comment by avanwinkle** [comment]
Thanks! The naming of player number properties has been a troublesome spot in MPF for a while, and in this case there were two code paths broadcasting a _player_added_ event and using different kwarg names for the player number.

I've pushed a fix to GMC to better handle the duplicate events, and created issue https://github.com/missionpinball/mpf/issues/1858 to track the MPF side and resolve the issue.
